# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b14c17a253e529777c113b6246264316f790e31572d83f7118e6a3153dae1462b2fcb69959ceb08b92011aaf95476f3d8be68c027e6a2920e5b4017c22d4ea7

test:
  secret_key_base: 5b25dc31c740a31f522233965207aa68e9e30fb1bb3cc8a41596328dc7dd7645a04e7ecc65fd87f86a1a201ba5856ef36f581d4a0d662d38d607c89c0fd96194

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
